name: Run Playwright Tests in Docker

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Docker
      run: 
        curl -fsSL https://get.docker.com | sudo bash
      
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version         

    - name: Build Docker Container
      run: |
        cd docker
        chmod +x build.sh start.sh
        ./build.sh
        ./start.sh

    - name: Install dependencies inside Docker 
      run: |
        docker exec booking-php-fpm sh -c "cd /application && npm install"
        docker exec booking-php-fpm sh -c "cd /application && npm install playwright"

    - name: Run Playwright tests inside Docker
      run:
        ./connect.sh
        cd /app
        docker exec -it playwright-container npx playwright test --reporter=html

    - name: Stop Docker Container 
      run: 
        cd docker
        ./stop.sh

    - name: Upload Playwright-test-report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-report
        path: playwright-report/

    - name: Add Playwright report to PR
      uses: mshick/add-pr-comment@v2
      with:
        message: "Playwright tests completed! Test report can be found through: playwright-report/index.html"